title: 梧桐
description: iOS软件工程师

url: http://wutongr.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: 主页
   url: /index.html
 - title: 关于
   url: /about
 - title: 联系
   url: /contact

social:
   github: wutongr
   twitter: wutongr
   facebook: wutongr
   email: zcfree8@gmail.com

google_analytics: "UA-68288127-1"
